blueprint:
  name: Z2M TRV Calibration + DEBUG
  description: Автоматическая калибровка термоголовки через Number с уведомлениями.
  domain: automation

  input:
    room_temp_sensor:
      name: Внешний датчик температуры
      selector:
        entity:
          domain: sensor
          device_class: temperature
    trv_climate:
      name: Термоголовка (Climate)
      selector:
        entity:
          domain: climate
    trv_calibration_number:
      name: Сущность калибровки (Number)
      selector:
        entity:
          domain: number
    min_delta_step:
      name: Минимальный порог срабатывания
      default: 0.1
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    min_calibration:
      name: Минимальный предел калибровки
      default: -5
      selector:
        number:
          min: -10
          max: 0
          step: 0.5
    max_calibration:
      name: Максимальный предел калибровки
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
    debug_mode:
      name: Режим отладки
      default: false
      selector:
        boolean:

mode: single

trigger:
  - platform: state
    entity_id: !input room_temp_sensor
  - platform: state
    entity_id: !input trv_climate
    attribute: local_temperature

action:
  - variables:
      room_sensor: !input room_temp_sensor
      trv_entity: !input trv_climate
      cal_number: !input trv_calibration_number
      debug: !input debug_mode

      t_room: "{{ states(room_sensor) | float(0) }}"
      t_trv: "{{ state_attr(trv_entity, 'local_temperature') | float(0) }}"
      current_offset: "{{ states(cal_number) | float(0) }}"
      
      # Новая формула: разница между датчиками + старый оффсет
      new_offset: "{{ (t_room - t_trv + current_offset) | round(1) }}"
      final_offset: "{{ new_offset | clamp(!input min_calibration, !input max_calibration) }}"

  # Блок дебага: сработает только если включен переключатель в настройках
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ debug }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TRV Debug: {{ area_name(trv_entity) }}"
              message: >
                Внешний датчик: {{ t_room }}°C
                Термоголовка видит: {{ t_trv }}°C
                Текущий оффсет в Z2M: {{ current_offset }}
                ---
                Рассчитанный новый оффсет: {{ final_offset }}
                Разница изменений: {{ (final_offset - current_offset) | abs | round(2) }}

  # Проверка: нужно ли обновлять?
  - condition: template
    value_template: "{{ (final_offset - current_offset) | abs >= (!input min_delta_step | float) }}"

  # Установка значения
  - service: number.set_value
    target:
      entity_id: !input trv_calibration_number
    data:
      value: "{{ final_offset }}"
