blueprint:
  name: Z2M TRV Calibration (Fixed Attribute)
  description: Автоматическая калибровка через current_temperature (Zigbee2MQTT)
  domain: automation

  input:
    room_temp_sensor:
      name: Внешний датчик температуры
      selector:
        entity:
          domain: sensor
          device_class: temperature
    trv_climate:
      name: Термоголовка (Climate)
      selector:
        entity:
          domain: climate
    trv_calibration_number:
      name: Сущность калибровки (Number)
      selector:
        entity:
          domain: number
    min_delta_step:
      name: Минимальный порог срабатывания
      default: 0.3
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
    min_calibration:
      name: Минимальный предел калибровки
      default: -5
      selector:
        number:
          min: -10
          max: 0
          step: 0.5
    max_calibration:
      name: Максимальный предел калибровки
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
    debug_mode:
      name: Включить отладку
      default: false
      selector:
        boolean:

mode: single

trigger:
  - platform: state
    entity_id: !input room_temp_sensor
  - platform: state
    entity_id: !input trv_climate
    # Указываем правильный атрибут и здесь
    attribute: current_temperature

action:
  - variables:
      room_sensor: !input room_temp_sensor
      trv_entity: !input trv_climate
      cal_number: !input trv_calibration_number
      min_step: !input min_delta_step
      min_limit: !input min_calibration
      max_limit: !input max_calibration
      debug: !input debug_mode

      t_room: "{{ states(room_sensor) | float(none) }}"
      # ИСПРАВЛЕНО: берем current_temperature
      t_trv: "{{ state_attr(trv_entity, 'current_temperature') | float(none) }}"
      current_offset: "{{ states(cal_number) | float(none) }}"

  # Защита: не считаем, если ТРВ показывает 0 или недоступна
  - condition: template
    value_template: >
      {{ t_room is not none and t_trv is not none and current_offset is not none 
         and t_room > 5 and t_trv > 5 }}

  - variables:
      calculated_offset: "{{ (t_room - t_trv + current_offset) | round(1) }}"
      final_offset: "{{ calculated_offset | clamp(min_limit, max_limit) }}"
      difference: "{{ (final_offset - current_offset) | abs }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ debug }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "Debug TRV: {{ state_attr(trv_entity, 'friendly_name') }}"
              message: >
                Датчик комнаты: {{ t_room }}°C
                ТРВ (current_temp): {{ t_trv }}°C
                Текущий оффсет: {{ current_offset }}
                Новый оффсет: {{ final_offset }}
                Результат: {{ 'ОБНОВЛЯЮ' if difference >= min_step|float else 'МАЛОЕ ИЗМЕНЕНИЕ' }}

  - condition: template
    value_template: "{{ difference >= min_step | float }}"

  - service: number.set_value
    target:
      entity_id: !input trv_calibration_number
    data:
      value: "{{ final_offset }}"
