blueprint:
  name: TRV calibration via external temperature
  description: 'Sync TRV local temperature with external room sensor using local_temperature_calibration (Zigbee2MQTT)'
  domain: automation

  input:
    room_temp_sensor:
      name: External room temperature sensor
      selector:
        entity:
          domain: sensor

    trv_local_temp_sensor:
      name: TRV local temperature sensor
      selector:
        entity:
          domain: sensor

    trv_calibration_sensor:
      name: TRV calibration sensor
      selector:
        entity:
          domain: sensor

    trv_mqtt_topic:
      name: TRV Zigbee2MQTT topic (without /set)
      description: 'Example: zigbee2mqtt/TRV_BEDROOM'
      selector:
        text:

    last_saved_temp:
      name: Helper - last saved temperature
      selector:
        entity:
          domain: input_number

    min_delta_step:
      name: Minimum temperature change (°C)
      default: 0.3
      selector:
        number:
          min: 0.1
          max: 1
          step: 0.1
          mode: slider

    min_calibration:
      name: Minimum TRV calibration
      default: -5
      selector:
        number:
          min: -10
          max: 0
          step: 0.5

    max_calibration:
      name: Maximum TRV calibration
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 0.5

    debug_mode:
      name: Debug mode
      default: false
      selector:
        boolean:

mode: single

trigger:
  - platform: state
    entity_id: !input room_temp_sensor

condition:
  - condition: template
    value_template: >
      {% set last = states(!input last_saved_temp) | float(0) %}
      {% set current = states(!input room_temp_sensor) | float(0) %}
      {{ (current - last) | abs >= !input min_delta_step }}

action:
  - variables:
      ext_temp: "{{ states(!input room_temp_sensor) | float }}"
      local_temp: "{{ states(!input trv_local_temp_sensor) | float }}"
      local_delta: "{{ states(!input trv_calibration_sensor) | float }}"
      new_delta: >
        {{ (ext_temp - local_temp + local_delta)
           | max(!input min_calibration)
           | min(!input max_calibration)
           | round(2) }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ !input debug_mode }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: TRV Calibration Debug
              message: >
                External: {{ ext_temp }} °C
                TRV: {{ local_temp }} °C
                Current offset: {{ local_delta }} °C
                New offset: {{ new_delta }} °C

  - service: mqtt.publish
    data:
      topic: "{{ !input trv_mqtt_topic }}/set/local_temperature_calibration"
      payload: "{{ new_delta }}"

  - service: input_number.set_value
    target:
      entity_id: !input last_saved_temp
    data:
      value: "{{ ext_temp }}"
