blueprint:
  name: TRV calibration via external temperature (dual trigger)
  description: Automatically calibrates TRV local temperature to match an external room sensor whenever the room or TRV sensor changes
  domain: automation

  input:
    room_temp_sensor:
      name: External room temperature sensor
      selector:
        entity:
          domain: sensor

    trv_climate:
      name: TRV climate device
      selector:
        entity:
          domain: climate

    min_delta_step:
      name: Minimum temperature change (°C) to trigger recalibration
      default: 0.3
      selector:
        number:
          min: 0.1
          max: 1
          step: 0.1

    min_calibration:
      name: Minimum TRV calibration
      default: -5
      selector:
        number:
          min: -10
          max: 0
          step: 0.5

    max_calibration:
      name: Maximum TRV calibration
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 0.5

    debug_mode:
      name: Debug mode
      default: false
      selector:
        boolean:

mode: single

trigger:
  - platform: state
    entity_id:
      - !input room_temp_sensor
      - !input trv_climate

action:
  - variables:
      ext_temp: "{{ states(!input room_temp_sensor) | float }}"
      local_temp: "{{ state_attr(!input trv_climate, 'local_temperature') | float }}"
      local_delta: "{{ state_attr(!input trv_climate, 'local_temperature_calibration') | float }}"
      new_delta: "{{ (ext_temp - local_temp + local_delta) | max(!input min_calibration) | min(!input max_calibration) | round(2) }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ !input debug_mode }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: TRV Calibration Debug
              message: >
                External: {{ ext_temp }} °C
                TRV: {{ local_temp }} °C
                Current offset: {{ local_delta }} °C
                New offset: {{ new_delta }} °C

  - service: climate.set_temperature_calibration
    target:
      entity_id: !input trv_climate
    data:
      temperature_calibration: "{{ new_delta }}"
